# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/private-subnet" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
      directory: "_example/public-private-subnet" # Location of package manifests
      schedule:
        interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
      directory: "_example/public-private-subnet-single-nat-gateway" # Location of package manifests
      schedule:
        interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
      directory: "_example/public-subnet" # Location of package manifests
      schedule:
        interval: "weekly"
