name: readme workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
  assignee:
    uses: clouddrove/github-shared-workflows/.github/workflows/readme.yml@master
    secrets:
      TOKEN : ${{ secrets.GITHUB }}
      SLACK_WEBHOOK_TERRAFORM: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}
