name: tf-checks
on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  tf-checks-private-subnet-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/private-subnet/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  tf-checks-basic-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/basic/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  tf-checks-public-private-subnet-single-nat-gateway-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/public-private-subnet-single-nat-gateway/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  tf-checks-complete-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  tf-checks-public-subnet-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/public-subnet/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
