name: tf-lint
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@feat/revert-tflint
    secrets:
      GITHUB: ${{ secrets.GITHUB }}


