name: tfsec
on:
  pull_request:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        if: github.event_name == 'pull_request'
        uses: triat/terraform-security-scan@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          soft_fail: true
          tfsec_actions_comment: true
          tfsec_actions_working_dir: ./_example
        continue-on-error: true